---
title: "00_all"
format: 
  html: 
    embed-resources: true
editor: visual
---

## Loading Libraries for including .qmd files

```{r}
library(quarto)
library(here)

```

# Loading of Data and Data Wrangling 

## Including Load file (01_load)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false

quarto_render(here("R/01_load.qmd"))
```

{{< include 01_load.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/01_load.html"), here("results/01_load.html"))
```

## Including Clean file (02_clean)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false  

quarto_render(here("R/02_clean.qmd"))
```

{{< include 02_clean.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/02_clean.html"), here("results/02_clean.html"))
```

## Including Augmentation file (03_augment)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false    

quarto_render(here("R/03_augment.qmd"))
```

{{< include 03_augment.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/03_augment.html"), here("results/03_augment.html"))
```

# Loading Analysis

## Including Describe (04_describe)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false    

quarto_render(here("R/04_describe.qmd"))
```

{{< include 04_describe.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/04_describe.html"), here("results/04_decribe.html"))
```

## Including Analysis 1 file (05_analysis_1)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false    

quarto_render(here("R/05_analysis_1.qmd"))
```

{{< include 05_analysis_1.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/05_analysis_1.html"), here("results/05_analysis_1.html"))
```

## Including Analysis 2 file (05_analysis_2)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false    

quarto_render(here("R/05_analysis_2.qmd"))
```

{{< include 05_analysis_2.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/05_analysis_2.html"), here("results/02_analysis_2.html"))
```

## Including Analysis 3 file (05_analysis_3)

```{r, echo = TRUE, warning = FALSE, message = FALSE}
#| output: false      

quarto_render(here("R/05_analysis_3.qmd"))
```

{{< include 05_analysis_3.qmd >}}

```{r, echo = TRUE, warning = FALSE, message = FALSE}
file.rename(here("R/05_analysis_3.html"), here("results/05_analysis_3.html"))
```

## 
