---
title: "01_load"
format: html
editor: visual
---

## Loading Libraries

```{r}
#Loading libraries
rm(list=ls())
library(here)
library(httr)
library(readr)
```

## Loading of raw data from url

```{r}
raw_dir <- here("_raw/")
data_dir <- here("data/")

if (!dir.exists(raw_dir)) {
  dir.create(path = raw_dir)
  message("Created directory: ", raw_dir)
}

if (!dir.exists(data_dir)) {
  dir.create(path = data_dir)
  message("Created directory: ", data_dir)
}

url <- "https://www.kaggle.com/api/v1/datasets/download/aadyasingh55/drug-dataset"
temp_zip <- tempfile(fileext = ".zip")   
temp_dir <- tempdir()  

response <- GET(url, write_disk(temp_zip, overwrite = TRUE))

unzip(temp_zip, exdir = temp_dir)

extracted_files <- list.files(temp_dir, full.names = TRUE)
message("Extracted files: ", paste(extracted_files, collapse = ", "))

csv_file <- grep("\\.csv$", extracted_files, value = TRUE)

dataset <- read_csv(csv_file[1])


```

## Saving raw data as csv in raw data folder

A raw data is stored in order to always have a original copy of the data used for the project.

```{r}
# Specify the file path with the new name
file_path <- file.path(raw_dir, "raw_data.csv")

# Save the dataframe as a CSV file
write.csv(dataset, file_path, row.names = FALSE)
```

## Saving raw data as tsv in data folder

The data is furthermore stored in the data folder, which will allow for augmenting and such for later use in analysis and visualization.

```{r}

save_path <- file.path(data_dir, "01_dat_load.tsv")

# Save the dataframe as a TSV file
write_tsv(dataset, save_path)

```
