---
title: "03_augment"
format: html
editor: visual
---

## Quarto

```{r}
library(tidyverse)
library(dplyr)
library(readr)
```

Application, name_API, Side_Effects skal tælles og have en count kolonne for hver.

use clean_data3

```{r}
# defining the augment (this shoudl be done when loading )
clean_data <- clean_data3
```

#### Making count variables for 'Side_Effects'

```{r}
aug_clean_data <- clean_data |>
  
  # Counting for each row, as nr. of side effects might differ
  rowwise() |>
  
  # mutating in order to make SE_count variable with sum of Column containing SE in         header as this refer to side       effects listed for each row 
  mutate(Side_Effects_count = sum(!is.na(c_across(contains("Side_Effects_")))))
  
```

#### Making count variable for 'name_API'

```{r}
aug_clean_data <- clean_data |>
  
  # Counting for each row, as nr. of side effects might differ
  rowwise() |>
  
  # mutating in order to make SE_count variable with sum of Column containing SE in         header as this refer to side       effects listed for each row 
  mutate(API_count = sum(!is.na(c_across(contains("name_API_")))))
```
